# Generated by Django 5.2.7 on 2025-10-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='incident_type',
            field=models.CharField(choices=[('CR-TEMP', 'CR-TEMP'), ('ASSAULT', 'Assault'), ('BURGLARY', 'Burglary'), ('THEFT', 'Theft')], default='crime_app', max_length=50),
            preserve_default=False,
        ),
    ]
