# Generated by Django 5.2.7 on 2025-10-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0002_alter_crimereport_incident_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='assigned_officer',
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20),
        ),
    ]
