# Generated by Django 5.2.7 on 2025-10-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
