# Generated by Django 5.2.7 on 2025-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0006_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimereport',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Crime Report', 'verbose_name_plural': 'Crime Reports'},
        ),
        migrations.AddField(
            model_name='crimereport',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='evidence_audio',
            field=models.FileField(blank=True, null=True, upload_to='evidence/audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='evidence_video',
            field=models.FileField(blank=True, null=True, upload_to='evidence/videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='incident_type',
            field=models.CharField(choices=[('CR-TEMP', 'CR-TEMP'), ('ASSAULT', 'Assault'), ('BURGLARY', 'Burglary'), ('THEFT', 'Theft'), ('ROBBERY', 'Robbery'), ('VANDALISM', 'Vandalism'), ('FRAUD', 'Fraud'), ('CYBERCRIME', 'Cyber Crime'), ('DRUG_OFFENSE', 'Drug Offense'), ('TRAFFIC_ACCIDENT', 'Traffic Accident'), ('DOMESTIC_VIOLENCE', 'Domestic Violence'), ('HARASSMENT', 'Harassment'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='crimereport',
            index=models.Index(fields=['status', 'date_reported'], name='crime_app_c_status_ccdd57_idx'),
        ),
        migrations.AddIndex(
            model_name='crimereport',
            index=models.Index(fields=['reporter', 'date_reported'], name='crime_app_c_reporte_0b4b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='crimereport',
            index=models.Index(fields=['department', 'date_reported'], name='crime_app_c_departm_16a46f_idx'),
        ),
    ]
