# Generated by Django 5.2.7 on 2025-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0007_alter_crimereport_options_crimereport_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
    ]
