# Generated by Django 5.2.7 on 2025-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0008_alter_crimereport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
